{% set name = "dimad" %}
{% set version = "1991.05.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dimad-org/dimad/archive/v{{ version }}.tar.gz
  sha256: fd3a3d46bc762f5b477cbc767abf11e19cd38a1e309dda3facb46abaae1ddf07

build:
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}         # [unix]
    - {{ stdlib("c") }}                 # [unix]
    - {{ compiler("m2w64_c") }}         # [win]
    - {{ compiler("m2w64_fortran") }}   # [win]
    - make
  run:
    - m2w64-gcc-libgfortran  # [win]

test:
  source_files:
    - demos
  commands:
    # Set up the input file before running dimad
    - cp demos/dem1.d fort.15
    - dimad

about:
  home: https://dimad-org.github.io/
  summary: DIMAD is a program which studies particle behavior in circular machines and in beamlines
  description: |
    DIMAD is a program which studies particle behavior in circular machines and in
    beamlines. The trajectories of the particles are computed according to the
    second order matrix formalism. DIMAD does not provide synchrotron motion
    analysis but can simulate it. The program provides the user with the
    possibility of defining arbitrary elements to tailor the program to specific
    uses.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://dimad-org.github.io/docs/
  dev_url: https://github.com/dimad-org/dimad/

extra:
  recipe-maintainers:
    - ken-lauer
